<<<<<<< HEAD
DROP DATABASE IF EXISTS card_db;
CREATE DATABASE card_db;
USE card_db;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
=======
DROP DATABASE IF EXISTS trw_db;
CREATE DATABASE trw_db;
>>>>>>> b51bc5765cd511af1fdbe61bf6bfe024fc232e2f
